FROM python:latest

WORKDIR /app

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .
EXPOSE 8000

RUN python manage.py makemigrations
ENTRYPOINT manage.py runserver