variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "region" {}
variable "project_name" {}
variable "cidr_block" {}
variable "public_subnet_az1_cidr" {}
variable "private_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_subnet_az2_cidr" {}
variable "engine" {}
variable "engine_version" {}     
variable "instance_class" {}     
variable "username" {}  
variable "password" {} 
variable "dbname" {}
variable "bucket_name" {}